export interface FileEntry {
  path: string;
  content: string;
  language: string;
  createdAt: number;
  updatedAt: number;
}

/**
 * In-memory virtual file system backed by a Map.
 * Stores files generated by AI responses.
 */
export class VirtualFS {
  private files = new Map<string, FileEntry>();

  /** Get all file paths sorted alphabetically */
  getPaths(): string[] {
    return Array.from(this.files.keys()).sort();
  }

  /** Get a file by path */
  getFile(path: string): FileEntry | undefined {
    return this.files.get(normalizePath(path));
  }

  /** Check if a file exists */
  has(path: string): boolean {
    return this.files.has(normalizePath(path));
  }

  /** Create or update a file */
  writeFile(path: string, content: string, language?: string): FileEntry {
    const normalized = normalizePath(path);
    const now = Date.now();
    const existing = this.files.get(normalized);

    const entry: FileEntry = {
      path: normalized,
      content,
      language: language ?? inferLanguage(normalized),
      createdAt: existing?.createdAt ?? now,
      updatedAt: now,
    };

    this.files.set(normalized, entry);
    return entry;
  }

  /** Delete a file */
  deleteFile(path: string): boolean {
    return this.files.delete(normalizePath(path));
  }

  /** Get all files as an array */
  getAllFiles(): FileEntry[] {
    return Array.from(this.files.values()).sort((a, b) =>
      a.path.localeCompare(b.path),
    );
  }

  /** Clear all files */
  clear(): void {
    this.files.clear();
  }

  /** Serialize to a plain array for JSON storage */
  toJSON(): FileEntry[] {
    return this.getAllFiles();
  }

  /** Restore from a serialized array */
  static fromJSON(entries: FileEntry[]): VirtualFS {
    const fs = new VirtualFS();
    for (const entry of entries) {
      fs.files.set(entry.path, entry);
    }
    return fs;
  }

  /** Get directory tree structure */
  getTree(): TreeNode {
    const root: TreeNode = { name: '/', path: '/', type: 'directory', children: [] };

    for (const filePath of this.getPaths()) {
      const parts = filePath.split('/').filter(Boolean);
      let current = root;

      for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        const isFile = i === parts.length - 1;
        const childPath = '/' + parts.slice(0, i + 1).join('/');

        let child = current.children?.find(c => c.name === part);
        if (!child) {
          child = {
            name: part,
            path: childPath,
            type: isFile ? 'file' : 'directory',
            children: isFile ? undefined : [],
          };
          current.children!.push(child);
        }
        if (!isFile) {
          current = child;
        }
      }
    }

    sortTree(root);
    return root;
  }
}

export interface TreeNode {
  name: string;
  path: string;
  type: 'file' | 'directory';
  children?: TreeNode[];
}

function sortTree(node: TreeNode): void {
  if (!node.children) return;
  node.children.sort((a, b) => {
    // Directories first, then alphabetical
    if (a.type !== b.type) return a.type === 'directory' ? -1 : 1;
    return a.name.localeCompare(b.name);
  });
  node.children.forEach(sortTree);
}

function normalizePath(path: string): string {
  // Ensure leading slash, collapse double slashes
  let p = path.replace(/\\/g, '/');
  if (!p.startsWith('/')) p = '/' + p;
  return p.replace(/\/+/g, '/');
}

const EXTENSION_MAP: Record<string, string> = {
  ts: 'typescript',
  tsx: 'tsx',
  js: 'javascript',
  jsx: 'jsx',
  html: 'html',
  css: 'css',
  json: 'json',
  md: 'markdown',
  py: 'python',
  sql: 'sql',
  yaml: 'yaml',
  yml: 'yaml',
  sh: 'bash',
  bash: 'bash',
  env: 'text',
  txt: 'text',
  svg: 'xml',
  xml: 'xml',
};

function inferLanguage(path: string): string {
  const ext = path.split('.').pop()?.toLowerCase() ?? '';
  return EXTENSION_MAP[ext] ?? 'text';
}
